@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/angular.puml
!include DEVICONS/mysql.puml
!include DEVICONS/go.puml

LAYOUT_LEFT_RIGHT()

title Diagrama de contêineres do Sistema de Gerenciamento de Ar-condicionado

Person(cliente, "Cliente", "Gerencia o agendamentos dos seus equipamentos")

System_Boundary(MeuAr, 'MeuAr') {
    Container(frontend, "Pagína do cliente", "Angular", "Gerencia todos os produtos", $sprite="angular")
    ContainerDb(base_dados, "Armazena os agendamentos", "MySQL", $sprite="mysql")
    Container(backend, "API que trata as requisições", "Go", $sprite="go")
}

System(telegram, "Telegram")
System(email, "Email")

Rel(cliente, frontend, "Requisita os dados dele em", "HTTPS")
Rel(frontend, backend, "Pede os dados via", "HTTPS/JSON")
Rel(backend, base_dados, "Pede os dados via", "HTTPS/JSON")
Rel(backend, telegram, "Envia uma menssagem", "HTTPS/JSON")
Rel(backend, email, "Envia um email", "SMPT")
@enduml
